//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixServiseTests.mqProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mqProxy.IMqService")]
    public interface IMqService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMqService/GetResultDocument", ReplyAction="http://tempuri.org/IMqService/GetResultDocumentResponse")]
        byte[] GetResultDocument(string idLpu, string idCaseMis, int documentType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMqService/GetResultDocument", ReplyAction="http://tempuri.org/IMqService/GetResultDocumentResponse")]
        System.Threading.Tasks.Task<byte[]> GetResultDocumentAsync(string idLpu, string idCaseMis, int documentType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMqServiceChannel : PixServiseTests.mqProxy.IMqService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MqServiceClient : System.ServiceModel.ClientBase<PixServiseTests.mqProxy.IMqService>, PixServiseTests.mqProxy.IMqService {
        
        public MqServiceClient() {
        }
        
        public MqServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MqServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MqServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MqServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetResultDocument(string idLpu, string idCaseMis, int documentType) {
            return base.Channel.GetResultDocument(idLpu, idCaseMis, documentType);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetResultDocumentAsync(string idLpu, string idCaseMis, int documentType) {
            return base.Channel.GetResultDocumentAsync(idLpu, idCaseMis, documentType);
        }
    }
}
